### ISSUE TITLE
Is it possible to get auth permission?

### ISSUE THREAD

**Issue by bruce-plutusds** [makerdao/testchain#31]
It seems like a really good test tool. However, in some cases, it is necessary to change the contract state variable for various scenario testing.

How can I get auth? Is it possible to share the private key with auth permission of the default snapshot?

**Comment by ethanbennett** [comment]
Good point @bruce-plutusds , I'll add this to the documentation. For the default account:

Address: `0x16Fb96a5fa0427Af0C8F7cF1eB4870231c8154B6`
Key: `474BEB999FED1B3AF2EA048F963833C686A0FBA05F5724CB6417CF3B8EE9697E`

This account has the authority to do pretty much anything in the system, and it starts with a balance of 400 MKR. Thanks for asking, and feel free to let us know if you have any further feedback on running or integrating this!

**Comment by bruce-plutusds** [comment]
Thank you
